berliCRM/berlicrm

libraries/nusoap/nusoap.php

this will allow user names with Umlauts and should improve Umlauts in entities also

changed nusoap class (used by Outlook plugin) to no longer decode utf8

---

include/events/VTEventTrigger.inc
languages/de_de/Vtiger.php
languages/en_us/Vtiger.php
modules/com_vtiger_workflow/VTWorkflowManager.inc

added missing labels, 
syntax fix,
fix for empty "dependent_on"

cumulative fixes

---

languages/de_de/Emails.php
languages/en_us/Emails.php
layouts/vlayout/modules/Emails/EmailPreview.tpl
modules/Emails/views/MassSaveAjax.php

added some language file changes of future features

introduced new email flag for failed deliveries

---

layouts/vlayout/modules/Users/ListViewHeader.tpl
layouts/vlayout/modules/Vtiger/resources/List.js

fixed bug where Active/Inactive User switch led to wrong search_key value on pagination

enabled sort order in Users ListView

---

db_update.php

(old: user format displayed, db format expected)

fix number field format issues

---

modules/Reports/models/ScheduleReports.php

removed : from Schedulded Reports filenames

---

include/QueryGenerator/QueryGenerator.php

Workflow filter use ID values, CustViews use firstname - lastname combination

added workaround for Workflow filters on ownerFields to QueryGenerator

---

kundenportal/Contacts/ContactsList.php
kundenportal/Documents/DocumentsList.php
kundenportal/Products/ProductList.php
kundenportal/Project/ProjectsList.php
kundenportal/Quotes/QuotesList.php
kundenportal/Services/ServiceList.php
kundenportal/footer.html

streamlined some Customerportal (German only) Javascript functions

---

modules/com_vtiger_workflow/VTSimpleTemplate.inc

improved readability and indention

removed reports_to references in Workflow Email Templates

---

data/CRMEntity.php
layouts/vlayout/modules/Vtiger/resources/Detail.js

fixed AjaxSave display issues for JSON strings

it's now possible to save JSON strings

---

include/QueryGenerator/QueryGenerator.php

display of 'assigned_user_id'/'smownerid' in field list still TO DO

fixed CustomView filters for Contact's additional Account fields

---

modules/Emails/PHPMailer/src/PHPMailer.php

no longer add empty 'Reply-To' addresses

disabled SMTP cert check

---

include/Webservices/LineItem/VtigerInventoryOperation.php

previously LineItems were lost

fixed Webservice Revise operation for Inventory modules

---

vtigerversion.php
vtlib/Vtiger/Link.php

added usage of sequence for Widgets

---

include/database/PearDatabase.php
include/fields/DateTimeField.php
layouts/vlayout/modules/Vtiger/dashboards/DashboardHeaderIcons.tpl

fixed some PHP Warnings

---

modules/Vtiger/views/Header.php

switched to https for helper pages

---

include/Webservices/VtigerModuleOperation.php
include/Webservices/WebserviceField.php

added additional information (blockname, id, helpinfo) to Webservice Describe operation

fixed Webservice Query permission check

---

layouts/vlayout/modules/Reports/ReportHeader.tpl

toggleButton div was included twice

19253 fproot Frank

---

modules/Contacts/Contacts.php

fix for Contacts workflows which contain the creation of an Event or Task

19328 fproot

---

modules/Calendar/models/Module.php

Fix bug active inactive Fields display. 'support_end_date' and 'birthday' in Calendar.

19343 eg Eugen

---

modules/Invoice/pdfcreator.php
modules/PurchaseOrder/pdfcreator.php
modules/Quotes/pdfcreator.php
modules/SalesOrder/pdfcreator.php

coding switched to UTF8
(Eugen: i have a Problem with commit of this changes (ö,ä,ü,ß) UTF8. It have not commit, if i have the file from berlicrm-1.0.0. The changes are shown, but GIT have not commited. In the end, i make changes of this manually in files with UTF8 in my Editor "Visual Studio Code")

19536 fproot

---

modules/Vtiger/actions/Save.php
modules/Vtiger/uitypes/Time.php

fixes the following issues for time field (correctly used in List View):
- saving with consideration of time zone
- display proper value in Detail View
- display proper Value in Edit View

19569 fproot

---

cron/modules/SalesOrder/RecurringInvoice.service

provide proper format for durations

19573 fproot

---

languages/de_de/Users.php

19474 fproot Frank

---

include/Webservices/Custom/getMultiRelations.php

exclude deleted entries
added documents

19585 fproot

---

modules/Documents/models/Record.php

improved file download of large files by chunks

19591 fproot

---

layouts/vlayout/modules/Vtiger/ComposeEmailForm.tpl

fixed "CC" issues when empty values were present. (Revision 19651).

fixed mailing Popup JS error when "To" was added by auto-complete

---

modules/Calendar/actions/SaveAjax.php
modules/Vtiger/uitypes/Time.php

Calendar fixes:
- GUI display
- task DB

19705 fproot

---

data/CRMEntity.php
db_update.php
languages/de_de/Vtiger.php
languages/en_us/Vtiger.php
layouts/vlayout/modules/Calendar/resources/CalendarView.js
modules/Calendar/Activity.php
modules/Calendar/RepeatEvents.php
modules/Calendar/actions/DragDropAjax.php
modules/Calendar/models/Record.php
modules/Vtiger/actions/DeleteAjax.php
resources/helper.js

series and the changes are in all events of the serie. You can delete one or all events from calendar view. You can change a event of the serie separately, it muss be no more present in the serie, so simple edit it to 'no recurringevent', and then it is no more in the serie.
If so changed series will be changed again, it is without the separately event, and create no a new one. So it is correct.

Calendar repeat events. Change one of the event from the

---

modules/Vtiger/views/EmailsRelatedModulePopup.php

this will help out modules where an email relation had been established retroactively

added more generic method to add email fields to search popup

---

modules/Contacts/Contacts.php

TO DO: move generic version of query to CRMEntity.php

reworked query that will fetch Emails for Contacts

---

include/Webservices/Custom/NewParser.php

manually add filter for corresponding activitytype to query

fixed Webservice QueryParser issue with Calendar module

---

data/CRMEntity.php

(this will help locate issues if e.g. a field is missing in a table)

distinguish between failed query and data that cannot be found

---

languages/de_de/Vtiger.php
languages/en_us/Vtiger.php
layouts/vlayout/modules/CustomView/EditView.tpl
layouts/vlayout/modules/CustomView/resources/CustomView.js

fix for view names with " char in name

move js code from tpl to js file for better debugging and operation

---

vtlib/ModuleDir/6.0.0/ModuleName.php
vtlib/tools/console.php

added modulenumberfield and put it in the default listview added descriptionblock and field

improved module creation by the following functions:

---

include/utils/utils.php

- added datetime for date_modified by user table content change

- reversed DB changes from Rev. 21592

---

modules/Settings/Profiles/models/Record.php

delete previous entries to make room for inserts
insert default values as missing export privileges will be interpreted as rights granted

fixed some more issues with Reports' permissions

---

vtlib/Vtiger/PackageUpdate.php

(example: "SimpleXMLElement Object ( [0] => 1 )" will be set to "1".)

to set explicit masseditable to correct value type.

---

include/Webservices/Create.php
include/Webservices/Revise.php
include/Webservices/Update.php
vtlib/Vtiger/Functions.php

Add validationfilter for Webservice uitype 23 and 5

Fixed problem where invalide date passed via webservice

---

vtlib/Vtiger/Functions.php

We talked about it and do not see any need for this check in image EXIF data, so I removed it.

removed check for php open tag in image EXIF data

---

include/ListView/ListViewController.php
languages/de_de/SalesOrder.php

avoid warning
added translations for new recurring frequency

avoid warning

---

vtlib/Vtiger/ModuleBasic.php

- related lists
- mod_no
- tables
- files

improved cleanup on module deletion

---

modules/Settings/Profiles/models/Record.php

improved SQL by using parameterized query

fix permission logic

---

vtlib/ModuleDir/6.0.0/ModuleName.php
vtlib/Vtiger/PackageImport.php

fixed ModuleName.php template description field

---

modules/Invoice/pdfcreator.php

merge of 2 files.

---

composer.json
composer.lock
modules/Invoice/pdfcreator.php

This commit starts to make use of PHP composer installed software libraries, composer is integrated in installation process and you have to take care of it, if you only do an update of your existing installation.

Integrated E-Invoice into the core, preparing Swiss QR invoicing as well

---

layouts/vlayout/modules/Vtiger/resources/RelatedList.js

added function to preview that shows message if on preview is available and fixed preview, fixed preview to be responsive while scrolling

added preview for all related lists,
